export const PRODUCT_NAME_MAX_LENGTH = 150;
export const PRODUCT_ATTRIBUTE_NAME_MAX_LENGTH = 50;
export const PRODUCT_ATTRIBUTE_VALUE_MAX_LENGTH = 255;
export const MAX_PRODUCT_ATTRIBUTES = 10;
export const MIN_PRODUCT_PRICE = 0.01;
